package Main;

public class Resources {
	public static String[] texts = {
			"Tạm biệt @, khóc xong rồi thì thôi cất gọn laptop của em vào góc, mình tạm thời không nhìn nhau em nhé. Mỗi lần nhìn thấy em anh sợ lại làm tim mình đau hơn. Anh không biết mình có vượt qua cú sốc này không nữa. Chờ em hơn chục tuần, để rồi nhận trái đắng như vậy. Game mua rồi cũng không muốn tải nữa. Anh chưa đủ chín chắn để chấp nhận sự thật này, chắc là vậy, nên anh đành ích kỷ vậy thôi. Chưa được 2 tháng mà, em có cần vội vã về quê vậy không? Bảo về, nhưng 10 năm r vẫn chưa thấy về? Anh cảm thấy như bị lừa vậy, công sức lo lắng cho em thừa rồi vì em chắc vẫn luôn hạnh phúc nơi quê nhà kia. Vừa chơi Phas được 1 ngày xong đã đi về quê luôn, tình yêu của anh với em chắc không đủ. Em thừa biết fan boy là ntn mà 😭, vậy mà em vẫn như vậy. Tạm biệt em, cho anh ích kỷ lần này nhé. Hẹn gặp lại khi em đã mạnh mẽ hơn, anh không quay lưng đi nhưng anh sẽ dừng lại.",
			"Người bạn @ của tôi bị bệnh ung thư hậu môn giai đoạn cuối khoảnh khắc 2 người bạn thân lâu năm ngồi lại bên nhau giờ chỉ đếm từng giây từng phút, tôi buồn lắm nhưng không thể thốt thành lời, dường như người bạn của tôi cũng hiểu ra vấn đề, anh ấy chỉ mỉm cười nhìn tôi lần cuối làm tim tôi thắt lại, mình đã cùng nhau thề hẹn sẽ đi với nhau đến già nhưng anh lại đi quá sớm. Anh nắm lấy tay tôi như muốn nói lên những tâm tư từ tận đáy lòng. Bằng chút hơi thở ít ỏi và yếu đuối cuối cùng của mình, anh ấy nói nhỏ vao tai toi rang nguyen vong truoc khi chet la đuoc sờ vào bờ đít mềm mại của bạn, the nen ban co the cho tôi sờ để anh ấy được ra đi thanh thản không?",
			"@ và một thằng béo cùng nhau đi vào khách sạn. Anh ta trông có vẻ không thoải mái cho lắm. Anh cùng hắn đi đến quầy lễ tân, nhận chìa khóa và đi thang máy lên tầng nhận phòng. Ở trong phòng, hắn khóa chặt cửa lại, để chìa khóa ở một nơi cao mà @ không thể với tới được. Hắn thả lỏng dây nịch, quần tuột xuống, lão móc con cu từ trong quần hắn ra. Đó là thứ đã phá biết bao nhiêu màng trinh của cô gái. Nó bốc mùi trông thật kinh tởm. Nó tập hợp những mùi khó chịu nhất vào trong một thứ. Mùi hôi của nước tiểu, mồ hôi, tinh trùng của những lần động giường trước. Hắn lấy cục thịt to tướng kia vỗ vào hai bên má @. “Nào, mút đi”. Hắn ngưng vỗ vào má và nói với @. @ miễn cưỡng ngậm lấy cục thịt của hắn. Vẻ mặt anh ấy trông cực kì khó chịu, như kiểu muốn xiên chết thằng mập kia. Đột nhiên, thằng béo lấy hai tay, giữ chặt đầu anh ta, thúc mạnh vào người mình. Những giọt nước mắt bắt đầu tràn ra, chắc cu của hắn đã thọc sâu vào trong họng anh ta. Hắn liên tục thúc mạnh, ra vào trong họng anh. Cái dòng sữa nóng của hắn liên tục rót thẳng xuống dạ dày anh ta chứ không rót vào miệng. Anh ta run người do cảm giác dạ dày nhột vì cái dòng sữa nóng kia. Ở @, Anh ta có vẻ đã ra rồi, vì cái quần sụp màu hồng của anh ta đã ướt nhẹp, tràn ra khỏi sàn.",
			"hôm đấy là 1 ngày đẹp trời tôi cùng @ đi dạo quanh con phố nhà tôi, chúng tôi cười nói rất vui vẻ bỗng nhiên @ bảo anh ấy khát nước thế là chúng tôi đánh ghé qua quán cafe gần đó. Ngồi đc 1 lúc thì đột nhiên có đám người xông vào mặc đồ bó màu đen nhìn như deep dark fantasy, do đít @ to quá 1 trong số bọn chúng liền bắt @ lại rồi đưa vào phòng nghỉ của quán cafe mặc kệ sự ngăn cản của tôi hắn vẫn ép @ vào trong phòng đó. Sau khi vào phòng hắn đẩy ngã @ lên giường và bắt đầu sờ soạng anh ấy, anh ấy chống trả quyết liệt r` hắn ta tức quá tát @ 1 cái rồi bắt đầu lấy con hàng hắn ra. Con hàng của hắn rất to như đc tiêm thuốc và rất bốc mùi, hắn ép @ bú thứ đó mặc dù anh ấy k muốn rồi hắn cầm lấy đầu @ ép anh ấy bú và hắn bắn thứ chất lỏng trắng trắng đó vào họng của @ và ép anh ấy nuốt nó. Sau đó có thêm 1 tên nữa tiến vào chúng bắt đầu cưỡng hiếp @ chúng thay nhau đ*t anh ấy biến anh ấy thành 1 fuck slave. Sau khoảng 2 - 3 tiếng chúng đã ra khỏi căn phòng đó tôi vội vã tiến vào căn phòng, 1 cảnh tượng thật kinh tởm mồm và đít @ chảy ra những thứ chất lỏng màu trắng, xung quanh là những thứ dụng cụ thủ dâm mà chúng đã sử dụng với @, còn về phía @ thì anh ấy trông thật tội nghiệp khuôn mặt anh ấy đầy những thứ chất lỏng màu trắng bây h anh ấy trông k khác gì 1 fuck slave",
			"Địt mẹ tôi muốn thụ tinh với @ vãi lồn . t muốn anh ấy sinh ra những đứa trẻ với cái vòng hông tuyệt đẹp đó . Ông vua nghiện tuyệt đẹp như là một nữ thần xuống trần gian để làm rửa tội ác của chúng ta làm ra.\r\n"
					+ "@ còn hơn một nữ phù thủy . t không thể không quỳ xuống để cúng bái mỗi khi t thấy hình dáng anh ấy được . t vừa cúng bái anh ấy và vừa thờ cúng . T sẽ thực hiện nhiều tội ác chiến tranh hơn cả chính quyền VNCH chỉ để liếm được ngọt nước mọng chảy ra từ làn da mượt mà của @ t muốn @ rên trong khi con tim t đang nằm cạnh anh ấy t muốn đc nghe thấy trái tim của @ đập trong khi cơ thể của t hòa hợp vào cơ thể của @ để linh hồn thể xác của chúng ta có thể đảo ngược và đan xen qua những tội ác kinh thánh của Đảng Cộng Sản Việt Nam.\r\n"
					+ "t muốn bú ti @ , hút những giọt nước dừa dinh dưỡng từ vú anh ấy trong khi @ từ từ sục con chim đang nứng của t , t sẽ đổ tinh dịch của @ vào trà của t rồi để chim t ngâm trong đó , tiếng khóc của anh ấy và t",
			"Trong khi bạn đang buồn chán thì rất có thể @ đang phải chịu đựng những cú thúc mạnh bạo từ phía sau của 1 gã bụng phệ nào đó, cả @ ấy giật giật theo từng nhịp thúc, mồ hôi nhễ nhại, mái tóc đen bóng của @ bị gã đó nắm và kéo ngửa về phía sau, bờ môi thơm tho ấy đang mở rộng há hốc, cặp mắt bồ câu xinh đẹp ngày nào đang trợn trắng lên, cái lưỡi mềm mại thò hẳn ra bên ngoài miệng, vắt sang 1 bên cùng dòng nước miếng đang chạy xuống chiếc cổ thon dài. Rồi bất chợt ông tỉnh giấc lại, thở hồng hộc và nhìn sang bên trái tay mình. Phù, thật may @ vẫn ở đấy, ở bên bạn chứ ko phải đang vui vẻ bên gã bụng phệ nào đấy.",
			"Mấy thằng ranh con trong đây đừng có nghĩ @ hay đùa trên cái mạng ảo này mà nghĩ ngoài đời @ là một thằng coder hèn hạ đéo dám ra đường hay trầm cảm, tự kỉ nhé. Thật ra @ đéo phải một thằng coder bệnh hoạn như chúng mày nghĩ đâu lũ óc cặc ạ. @ đây là hacker đàng hoàng chân chính nhá. Kể từ khi lọt lòng tới nay @ đã hack hơn 10 triệu game và từ việc hack game mỗi ngày @ đã thông thạo được 50 ngôn ngữ lập trình cùng với khả năng đọc vị bất kỳ ai. Chưa hết đâu. Kể từ năm 2077, khi mà xem sex, @ đã giác ngộ được mọi triết lý trên đời và quyết tâm xem cho bằng được sếch. Vì lẽ đó nên @ đã build máy tính khủng xem được trên 1000TB sếch (Gấp 10 lần máy Kiên Trung). Và chưa đầy nửa năm @ đã luyện thành mình đồng da sếch, chỉ cần thằng nào đụng đến @ thì một cái búng tay cũng đủ để nó bị sếch ngay lập tức với tốc độ gấp 10 lần tốc độ ánh sáng. Nếu thằng nào trong này cả gan chửi @ thì nên biết @ là ai trước đi, đề phòng bị sếch khi nào không hay đấy.",
			"Trong trường hợp anh bị say đắm bởi vẻ đẹp quyến rũ của @ (hoặc những vẻ đẹp tương tự của @), anh khẳng định anh không liên hệ bởi bất cứ một cô gái khác nào trong nhóm này, có lẽ trái tim của anh chỉ dành cho @. Anh cũng xin khẳng định anh không hề có thể yêu một cô gái nào khác khi đã yêu @. ",
			"Xin lỗi nhưng mình tò mò quá nên có vào fb của bạn @ xem qua, mình thấy bạn hơi trẻ trâu, có vẻ giống mình của 4,5 năm trước nên mình hiểu, hiện tại thì chắc là do bạn chưa biết cách hoà đồng với mọi người, cái này thì đơn giản thôi, bạn cứ nhiệt tình giúp đỡ mọi người, bất kể việc gì nếu nó nằm trong khả năng của bạn, nhưng coi trừng kẻo bị lợi dụng, và không cần nhất thiết phải chơi với mọi người, chỉ cần tìm vài ba đứa bạn thân để chơi là được rồi, chúc bạn sớm hoà nhập được với cộng đồng",
			"Con đàn bà ác độc @ kia, mày xứng đáng bị đánh đập, bị hiếp dâm bởi những người đàn ông mà mày đã lừa gạt. Một đứa con gái bề ngoài nam thanh nữ tú, bên trong là một con điếm chính hiệu chỉ biết lừa lọc người khác. Mày chỉ là một con điếm chỉ biết bào mòn tiền bạc và sức khỏe của những người đàn ông chân lắm tay bùn. Mày có biết cảm giác của họ khi bị mày lừa gạt không? Mày có sung sướng khi đang sử dụng những đồng tiền mà mày đã lừa gạt của họ không? Hay là mày có cảm thấy áy náy, khi mà họ từ một người đàn ông quyền quý, trở thành một con nợ không? Liệu mày còn lương tâm để cắn rứt nữa không? Tao đã chịu đựng mày quá đủ rồi @ ạ. Tao ước tao chưa từng phải vướng vào tiếng sét ái tình đầy cạm bẫy này. Và tao cũng ước, rằng mày không được sinh ra.\r\n"
					+ "Hỡi chúa Barbatos hãy trừng trị con điếm này như cách nó đã làm đối với đàn ông chúng con.\r\n"
					+ "Hỡi chúa Jesus hãy tước đi quyền được sống trên thiên đàng, đày áp nó xuống địa ngục tăm tối.\r\n"
					+ "Hỡi quỷ Satan hãy cho con quỷ này tiền bạc, sau đó tước đi quyền hạnh phúc trong cuộc đời của nó.\r\n"
					+ "Hỡi những đứa con của Cộng Sản, hãy tống con điếm này vào trại cải tạo dành cho lũ phản động, để cho nó biết mùi đau khổ mà cánh đàn ông đã trải qua.\r\n"
					+ "Hỡi những người con dân chủ giãy chết, hãy giải cứu con điếm @ khỏi tay Cộng Sản, sau đó ban phát cho nó những quả bom dân chủ.\r\n"
					+ "Hỡi những người theo phát xít, hãy bành trướng tử cung nó bằng tinh trùng, như cách mà các người đã làm trong Thế Chiến Thứ Hai.\r\n"
					+ "Hỡi những người đàn ông chân chính, hãy đứng dậy đấu tranh giành lại những gì đã mất vào tay con điếm @." };
}
