package aylesw.meteor.simsimi;

import java.util.HashMap;

public class LanguageCode {
    public static final HashMap<String, String> languageCodes = new HashMap<String, String>() {{
        put("af", "Afrikaans");
        put("al", "Shqip");
        put("ar", "العربية");
        put("as", "অসমীয়া");
        put("az", "Azərbaycanca");
        put("be", "Беларуская");
        put("bg", "Български");
        put("bn", "বাংলা");
        put("br", "Brezhoneg");
        put("bs", "Bosanski");
        put("ca", "Català");
        put("ch", "中文(繁體)");
        put("cs", "Čeština ");
        put("cx", "Cebuano");
        put("cy", "Cymraeg");
        put("da", "Dansk");
        put("de", "Deutsch");
        put("el", "Ελληνικά");
        put("en", "English");
        put("es", "Español");
        put("et", "Eesti");
        put("eu", "Euskara");
        put("fa", "فارسی");
        put("fi", "Suomi");
        put("fr", "Français");
        put("fy", "Frysk");
        put("gl", "Galego");
        put("gn", "Avañe'ẽ");
        put("gu", "ગુજરાતી");
        put("he", "עברית");
        put("hi", "हिन्दी");
        put("hr", "Hrvatski");
        put("hu", "Magyar");
        put("hy", "Հայերեն");
        put("id", "Bahasa Indonesia");
        put("is", "Íslenska");
        put("it", "Italiano");
        put("ja", "日本語");
        put("jv", "Basa Jawa");
        put("ka", "ქართული");
        put("kh", "ខ្មែរ");
        put("kk", "Қазақ тілі");
        put("kn", "ಕನ್ನಡ");
        put("ko", "한국어");
        put("ku", "Kurdî (Kurmancî)");
        put("lt", "Lietuvių");
        put("lv", "Latviešu");
        put("mk", "Македонски");
        put("ml", "മലയാളം");
        put("mn", "Монгол");
        put("mr", "मराठी");
        put("ms", "Bahasa Melayu");
        put("my", "ဗမာစာ");
        put("nb", "Norsk (Bokmål)");
        put("ne", "नेपाली");
        put("nl", "Nederlands");
        put("or", "ଓଡ଼ିଆ");
        put("pa", "ਪੰਜਾਬੀ");
        put("ph", "Filipino");
        put("pl", "Język polski");
        put("ps", "پښتو");
        put("pt", "Português");
        put("ro", "Română");
        put("rs", "Српски");
        put("ru", "Русский<");
        put("rw", "Ikinyarwanda");
        put("si", "සිංහල");
        put("sk", "Slovenčina");
        put("sl", "Slovenščina");
        put("sv", "Svenska");
        put("sw", "Kiswahili");
        put("ta", "தமிழ்");
        put("te", "తెలుగు");
        put("tg", "Тоҷикӣ");
        put("th", "ไทย");
        put("tr", "Türkçe");
        put("uk", "Українська");
        put("ur", "اردو");
        put("uz", "O'zbek");
        put("vn", "Tiếng Việt");
        put("zh", "中文(简体)");
    }};
}
